# Generated by Django 5.0 on 2023-12-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=50)),
                ('remark', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'cash flow',
                'verbose_name_plural': 'cash flows',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExpenseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('cash_out', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopflee.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('cash_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopflee.cashflow')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopflee.category')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCashIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='update', max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('income_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopflee.incomesource')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='update', max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expense_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopflee.expensesource')),
            ],
        ),
    ]
