# Generated by Django 5.0 on 2023-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesource',
            name='cash_flow',
        ),
        migrations.RemoveField(
            model_name='expensesource',
            name='cash_flow',
        ),
        migrations.RemoveField(
            model_name='expensesource',
            name='cash_out',
        ),
        migrations.RemoveField(
            model_name='incomesource',
            name='cash_in',
        ),
        migrations.AlterField(
            model_name='updatecashin',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Scheduled', 'Scheduled')], default='update', max_length=50),
        ),
        migrations.AlterField(
            model_name='updatecashout',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='update', max_length=50),
        ),
        migrations.DeleteModel(
            name='CashFlow',
        ),
    ]
