# Generated by Django 5.0 on 2023-12-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0003_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='actual_cash_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='actual_cash_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
