# Generated by Django 5.0 on 2023-12-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0006_delete_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
