# Generated by Django 5.0 on 2023-12-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0009_summary_actual_balance_summary_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='actual_balance',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='planned_balance',
        ),
    ]
