# Generated by Django 5.0 on 2023-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0010_remove_summary_actual_balance_remove_summary_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
