# Generated by Django 5.0 on 2023-12-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0013_balance_actual_balance_balance_planned_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='actual_balance',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='planned_balance',
        ),
    ]
