# Generated by Django 5.0 on 2023-12-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0014_remove_balance_actual_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
