# Generated by Django 5.0 on 2023-12-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0015_delete_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planned_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
