# Generated by Django 5.0 on 2023-12-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0016_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
