# Generated by Django 5.0 on 2023-12-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0018_availablebalance_summary_actual_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableBalance',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='actual_balance',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='planned_balance',
        ),
    ]
