# Generated by Django 5.0 on 2023-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0020_availablebalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableBalance',
        ),
        migrations.AddField(
            model_name='summary',
            name='actual_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='summary',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='summary',
            name='planned_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
