# Generated by Django 5.0 on 2023-12-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0021_delete_availablebalance_summary_actual_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='summary',
            name='available_balance',
        ),
    ]
