# Generated by Django 5.0 on 2023-12-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0022_availablebalance_remove_summary_available_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
