# Generated by Django 5.0 on 2023-12-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0023_summary_available_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='available_balance',
        ),
    ]
