# Generated by Django 5.0 on 2023-12-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0025_delete_availablebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
