# Generated by Django 5.0 on 2023-12-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0026_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
