# Generated by Django 5.0 on 2023-12-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0027_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
