# Generated by Django 5.0 on 2023-12-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0029_alter_updatecashout_expense_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecashout',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
