# Generated by Django 5.0 on 2023-12-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0030_updatecashout_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatecashout',
            name='processed',
        ),
    ]
