# Generated by Django 5.0 on 2023-12-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0031_remove_updatecashout_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecashin',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
