# Generated by Django 5.0 on 2023-12-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0033_updatecashout_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatecashin',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='updatecashout',
            name='processed',
        ),
    ]
