# Generated by Django 5.0 on 2024-01-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0035_updatecashin_processed_updatecashout_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_actual_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_actual_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
            },
        ),
    ]
