# Generated by Django 5.0 on 2024-01-06 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0036_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopflee.summary'),
        ),
    ]
