# Generated by Django 5.0 on 2024-01-06 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0038_remove_dashboard_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSummaryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopflee.dashboard')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopflee.summary')),
            ],
        ),
    ]
