# Generated by Django 5.0 on 2024-01-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0039_dashboardsummaryrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardSummaryRelation',
        ),
    ]
