# Generated by Django 5.0 on 2024-02-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0041_updatecashout_priority_level_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecashin',
            name='division',
            field=models.CharField(choices=[('catalyst', 'Catalyst'), ('oil_and_gas', 'Oil and Gas'), ('general_chemicals', 'General Chemicals'), ('overhead', 'Overhead')], default='update', max_length=50),
        ),
        migrations.AddField(
            model_name='updatecashin',
            name='projects',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='updatecashout',
            name='division',
            field=models.CharField(choices=[('catalyst', 'Catalyst'), ('oil_and_gas', 'Oil and Gas'), ('general_chemicals', 'General Chemicals'), ('overhead', 'Overhead')], default='update', max_length=50),
        ),
        migrations.AddField(
            model_name='updatecashout',
            name='projects',
            field=models.CharField(default='', max_length=250),
        ),
    ]
