# Generated by Django 5.0 on 2024-02-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatecashin',
            old_name='division',
            new_name='cost_center',
        ),
        migrations.RenameField(
            model_name='updatecashout',
            old_name='division',
            new_name='cost_center',
        ),
    ]
